/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthUnauthorizedRouteImport } from './routes/auth.unauthorized'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as RoomRoomRouteImport } from './routes/room.$room'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/auth/unauthorized',
  path: '/auth/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomRoute = RoomRoomRouteImport.update({
  id: '/room/$room',
  path: '/room/$room',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/campaigns': typeof CampaignsRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/room/$room': typeof RoomRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/campaigns': typeof CampaignsRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/room/$room': typeof RoomRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/campaigns': typeof CampaignsRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/room/$room': typeof RoomRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/campaigns'
    | '/auth/unauthorized'
    | '/invite/$token'
    | '/room/$room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/campaigns'
    | '/auth/unauthorized'
    | '/invite/$token'
    | '/room/$room'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/campaigns'
    | '/auth/unauthorized'
    | '/invite/$token'
    | '/room/$room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CampaignsRoute: typeof CampaignsRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RoomRoomRoute: typeof RoomRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/unauthorized': {
      id: '/auth/unauthorized'
      path: '/auth/unauthorized'
      fullPath: '/auth/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$room': {
      id: '/room/$room'
      path: '/room/$room'
      fullPath: '/room/$room'
      preLoaderRoute: typeof RoomRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CampaignsRoute: CampaignsRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  InviteTokenRoute: InviteTokenRoute,
  RoomRoomRoute: RoomRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
